services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./src
          target: /var/www/html

  php:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: bitnami/php-fpm:latest
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=vladyslavshusharin
    restart: unless-stopped

  nodeapp:
    build: .
    container_name: my_node_js
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: package.json


